version: "3"
services:
  db:
    image: 'postgres:latest'
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 8001:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped

  app:
    image: 'feedback-service:latest'
    network_mode: bridge
    container_name: app
    build:
      context: .
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - db
    links:
      - db
volumes:
  postgres-data: